package com.maven.demo.entity;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;

import java.time.LocalDateTime;

@Getter
@Setter
@Entity
public class PasswordResetToken {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    private String code; // Store the verification code here

    @ManyToOne
    private UserEntity user;

    private LocalDateTime expiryDate = LocalDateTime.now().plusMinutes(15); // Optional: Expiry time

    // No-argument constructor required by Hibernate
    public PasswordResetToken() {
        // Default constructor
    }

    // Constructor to initialize with code and user
    public PasswordResetToken(String code, UserEntity user) {
        this.code = code;
        this.user = user;
    }

    // Getters and Setters (Generated by Lombok)
}
